clear all; clc; close all;

%% set parameters
% NOTE1: .mat files for videos generated by the script named "main1~" are required to run this script.
% NOTE2: Fig. 8 was generated using 'iPhoneVideo1', 'iPhoneVideo3', 'iPhoneVideo5', 'iPhoneVideo6', 'iPhoneVideo8', 'iPhoneVideo10', 'iPhoneVideo11', 'iPhoneVideo12', 'iPhoneVideo14', 'iPhoneVideo15'

videoFileName_arr = {'iPhoneVideo1', 'iPhoneVideo3', 'iPhoneVideo5', 'iPhoneVideo6', 'iPhoneVideo8',...
    'iPhoneVideo10', 'iPhoneVideo11', 'iPhoneVideo12', 'iPhoneVideo14', 'iPhoneVideo15'};

targetLocalSNR_dB_arr = [30, 25, 20, 15, 10];
numOfRealizations = 5;

func_compDirectConcatAndPeriodicZeroingOut (videoFileName_arr, targetLocalSNR_dB_arr, numOfRealizations);

